name: Deploy app to heroku

# When
on:
  push: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.9.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "githubactions"
          heroku_email: ${{secrets.REPO_EMAIL}}
