name: PR checklist checker

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [master]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: PR checklist checker
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: npm install @actions/core @actions/github
      - uses: ./.github/actions/pr-checklist-checker
